name: CD/CI and Build for All OS

on:
  push:
    branches: [ main ]
    tags: [ '*' ]   # Add this line to trigger on any tag
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: make install

      # - name: Build with Make
      #   run: make all

      - name: Create dist folder
        run: mkdir -p dist

      - name: Build with PyInstaller
        run: pyinstaller --name App --onefile --windowed --icon=assets/logo.ico app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyqt6_simple_app_${{ runner.os }}
          path: |
            dist/app.exe
            dist/app
            dist/app.app

      - name: Install libegl1 (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/app.exe
            dist/app
            dist/app.app